# Generated by Django 6.0.5 on 2026-05-07 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='rutina',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='descanso',
            field=models.PositiveIntegerField(blank=True, help_text='segundos entre series', null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='peso_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='altura',
            field=models.PositiveIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_experiencia',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('entrenador', 'Entrenador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
        migrations.CreateModel(
            name='DiaRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('nombre', models.CharField(blank=True, help_text='Ej: Push, Piernas, Torso', max_length=100)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='gym.rutina')),
            ],
            options={
                'ordering': ['dia'],
                'unique_together': {('rutina', 'dia')},
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='dia_rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='gym.diarutina'),
        ),
    ]
