# Generated by Django 6.0.5 on 2026-05-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_ejercicio_rutina_ejercicio_descanso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wger_id', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('musculo_principal', models.CharField(blank=True, max_length=100)),
                ('equipamiento', models.CharField(blank=True, max_length=100)),
                ('imagen_url', models.URLField(blank=True, max_length=500)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ejercicio del catálogo',
                'verbose_name_plural': 'Catálogo de ejercicios',
                'ordering': ['nombre'],
            },
        ),
    ]
