# Generated by Django 6.0.5 on 2026-05-27 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_ejerciciocatalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_recibido', to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_dado', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='gym.rutina')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SerieRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('ejercicio_registrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='gym.ejercicioregistrado')),
            ],
            options={
                'ordering': ['numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
                ('dia_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='gym.diarutina')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='gym.rutina')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='ejercicioregistrado',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_registrados', to='gym.sesion'),
        ),
    ]
